config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  concern :votable do
    member do
      post :rating_up, :rating_down
      delete :revote
    end
  end

  resources :questions, concerns: :votable, shallow: true do
    resources :answers, concerns: :votable, only: [:create, :edit, :update, :destroy] do
      patch :best, on: :member
    end
  end

  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :badges, only: :index

  root to: "questions#index"
end

app/models/answer.rb
class Answer < ApplicationRecord
  ANSWERS_COUNT = 1

  include Votable

  belongs_to :question
  belongs_to :user

  has_many_attached :files, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable


  validates :body, presence: true
  validate :best_count, on: :best

  accepts_nested_attributes_for :links, reject_if: :all_blank

  default_scope -> { order('best DESC, created_at') }
  scope :best, -> { where(best: true) }

  def best!
    transaction do
      question.answers.best.update_all(best: false)
      update!(best: true)
      user.award_badge!(question.badge) if question.badge.present?
    end
  end

  private

  def best_count
    errors.add(:answer, 'only one answer can be the best') if question.answers.best.count > ANSWERS_COUNT
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  belongs_to :question
  belongs_to :user, optional: true
  has_one_attached :image, dependent: :destroy

  validates :title, presence: true
end

app/models/concerns/votable.rb
module Votable
  extend ActiveSupport::Concern

  included do
    has_many :votes, as: :votable, dependent: :destroy
  end

  def rating_up(user)
    vote(user, 1)
  end

  def rating_down(user)
    vote(user, -1)
  end

  def rating_sum
    votes.sum(:rating)
  end

  private

  def vote(user, rate)
    votes.create!(user: user, rating: rate) unless user.voted?(self)
  end
end

app/models/link.rb
class Link < ApplicationRecord
  GIST_URL = "gist.github.com"
  URL_VALID = /(ftp|http|https):\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?/
  belongs_to :linkable, polymorphic: true

  validates :name, :url, presence: true
  validates :url, format: { with: URL_VALID, message:'has invalid' }

  def gist?
    URI(url).host == GIST_URL
  end

  def gist_content
    client = Octokit::Client.new(access_token: ENV['GITHUB_SECRET_TOKEN'])
    gist = client.gist(url.split("/").last)
    file = {}
    gist.files.each { |_, v| file = v }
    file.content
  end
end

app/models/question.rb
class Question < ApplicationRecord
  include Votable

  has_many :answers, dependent: :destroy
  belongs_to :user
  has_many_attached :files, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  has_one :badge, dependent: :destroy

  accepts_nested_attributes_for :links, reject_if: :all_blank
  accepts_nested_attributes_for :badge, reject_if: :all_blank

  validates :title, :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :questions
  has_many :answers
  has_many :badges
  has_many :votes

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def author?(obj)
    obj.user_id == id
  end

  def award_badge!(badge)
    badges << badge
  end

  def voted?(item)
    votes.exists?(votable: item)
  end

end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :votable, polymorphic: true
  belongs_to :user

  validates :user_id, uniqueness: { scope: [:votable_type, :votable_id] }
  validates_inclusion_of :rating, in: -1..1
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted
  
  before_action :authenticate_user!
  before_action :find_question, only: [:create]
  before_action :find_answer, only: [:update, :destroy, :best]

  def create
    @answer = @question.answers.new(answers_params)
    @answer.user = current_user
    flash[:notice] = 'Your answers successfully created.' if @answer.save
  end

  def update
    if current_user.author?(@answer)
      @answer.update(answers_params)
      @question = @answer.question
    else
      head :forbidden
    end
  end

  def destroy
    if current_user.author?(@answer)
      @answer.destroy
      flash[:notice] = 'Answer successfully deleted.'
    else
      flash[:notice] = 'You not a author.'
      redirect_to @answer.question
    end
  end

  def best
    @answer.best! if current_user.author?(@answer.question)
  end


  private

  def find_question
    @question = Question.with_attached_files.find(params[:question_id])
  end

  def answers_params
    params.require(:answer).permit(:body, files: [], links_attributes: [:name, :url])
  end

  def find_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def redirect_to_answer
    redirect_to @answer.question
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_attachment

  def destroy
    if current_user.author?(@attachment.record)
      @attachment.purge
    else
      redirect_to questions_path
    end
  end

  private

  def find_attachment
    @attachment = ActiveStorage::Attachment.find(params[:id])
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :authenticate_user!

  def index
    @badges = current_user.badges
  end
end

app/controllers/concerns/voted.rb
module Voted
  extend ActiveSupport::Concern

  included do
    before_action :set_votable, only: [ :rating_up, :rating_down, :revote]
  end

  def rating_up
    unless current_user.author?(@votable)
      @votable.rating_up(current_user)
      render_json
    end
  end

  def rating_down
    unless current_user.author?(@votable)
      @votable.rating_down(current_user)
      render_json
    end
  end

  def revote
    unless current_user.author?(@votable)
      @votable.votes.find_by(user_id: current_user)&.destroy
      render_json
    end
  end

  private

  def render_json
    render json: { rating: @votable.rating_sum, klass: @votable.class.to_s, id: @votable.id }
  end

  def model_klass
    controller_name.classify.constantize
  end

  def set_votable
    @votable = model_klass.find(params[:id])
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :authenticate_user!
  before_action :find_link

  def destroy
    if current_user.author?(@link.linkable)
      @link.destroy
      flash[:notice] = 'Link successfully deleted.'
      # redirect_to request.referrer, notice: 'Link successfully deleted.'
    else
      redirect_to @link.linkable
      flash[:notice] = 'Only author can deleted Link.'
    end
  end

  private

  def find_link
    @link = Link.find(params[:id])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted

  before_action :authenticate_user!, except: [:index, :show, :rating_up, :rating_down]
  before_action :load_question, only: [:show, :edit, :update, :destroy]

  def index
    @questions = Question.all
  end

  def show
    @answer = Answer.new
    @answer.links.new
  end

  def new
    @question = current_user.questions.new
    @question.links.new
    @question.badge ||= Badge.new
  end

  def edit
  end

  def create
    @question = current_user.questions.new(question_params)

    if @question.save
      redirect_to @question, notice: 'Your question successfully created.'
    else
      render :new
    end
  end

  def update
    if current_user.author?(@question)
      @question.update(question_params)
    else
      head :forbidden
    end
  end

  def destroy
    if current_user.author?(@question)
      @question.destroy
      redirect_to questions_path, notice: 'Question successfully deleted.'
    else
      redirect_to @question, notice: 'Only author can delete question.'
    end
  end

  private

  def load_question
    @question = Question.with_attached_files.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, files: [], links_attributes: [:name, :url], badge_attributes: [:title, :image])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_answer.html.slim
div class = "answer#{answer.id}"
  div class = "answer#{answer.id}-errors"
  - if answer.persisted?
    - if answer.best?
      div class = "best#{answer.id}"
        .best_answer
          h1= 'BestAnswer'
          p= answer.body
    - else
        p= answer.body

    .vote
      = render 'shared/vote', resource: answer

    .links
      p Links:
      ul
        = render answer.links, resource: answer

    - if answer.files.attached?
      - answer.files.each do |file|
        div class = "attachment-#{file.id}"
          p= link_to file.filename.to_s, url_for(file)
          - if current_user&.author?(answer)
            = link_to 'remove', attachment_path(file), class: 'delete-attachment-link', remote: true, method: :delete

    - if current_user&.author?(answer)
      p= link_to 'Edit', '#answer_id', class: 'edit-answer-link', data: { answer_id: answer.id }
      p= link_to 'Delete answer', answer_path(answer), class: 'delete-answer-link', remote: true, method: :delete, data: {answer_id: answer.id}

    = form_with model: answer, class: 'hidden', html: { id: "edit-answer-#{answer.id}" } do |f|
      p
        = f.label :body, 'Your answer'
        = f.text_area :body
      p
        = f.label :files
        = f.file_field :files, multiple: true, direct_upload: true
      p Links:
      p
        = f.fields_for :links do |l|
        .links
          = link_to_add_association 'add link', f, :links
        p
        = f.submit 'Save Edit'
    - if current_user&.author?(answer.question) && !answer.best?
      p= link_to 'Choose the best', best_answer_path(answer), class: 'best-answer-link', remote: true, method: :patch

app/views/answers/_form.html.slim
.answer-errors
  = render 'shared/errors', resource: @answer
= form_with model: [@question, @answer], class: 'new-answer' do |f|
  = f.label :body, 'Answer'
  = f.text_area :body
  = f.label :files
  = f.file_field :files, multiple: true
  p Links:
  p
    =f.fields_for :links do |l|
      = render 'link_fields', f: l
    .links
      = link_to_add_association 'add link', f, :links
  = f.submit 'Answer'

app/views/answers/_link_fields.html.slim
.nested-fields
  = f.label :name, 'Link'
  = f.text_field :name
  = f.label :url
  = f.text_field :url
  = link_to_remove_association "remove task", f

app/views/answers/best.js.erb
$('.answers').html('<%= j render @answer.question.answers %>')

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');
$(".notice").html("<%=j flash[:notice] %>");

<% if @answer.persisted? %>
  $('.answers').append('<%= j render @answer %>');
  $('.new-answer #answer_body').val('');
<% end %>

app/views/answers/destroy.js.erb
$(".notice").html("<%=j flash[:notice] %>");
$('.answer<%= @answer.id %>').remove();

app/views/answers/update.js.erb
<% answer_id = ".answer#{@answer.id}" %>

<% if @answer.errors.present? %>
  $('<%= answer_id+"-errors" %>').prepend('<%= render 'shared/errors', resource: @answer %>');
<% else %>
  $(".notice").html("<%=j flash[:notice] %>");
  $('<%= answer_id %>').html('<%= j render @answer %>');
<% end %>

app/views/attachments/destroy.js.erb
$('.attachment-<%= @attachment.id %>').remove();

app/views/badges/index.html.slim
- @badges.each do |badge|
  p= link_to badge.question.title, question_path(badge.question)
  = image_tag badge.image, title: badge.title, size: "70x70"
  p= badge.title

app/views/links/_link.html.slim
div class = "link#{link.id}"
  - if link.gist?
    = link.gist_content
  - else
    li= link_to link.name, link.url, target: :blank
    
  - if current_user&.author?(resource)
    = link_to 'remove', link_path(link), class: 'delete-link-link', remote: true, method: :delete

app/views/links/destroy.js.erb
$(".notice").html("<%=j flash[:notice] %>");
$('.link<%= @link.id %>').remove();

app/views/questions/_form.html.slim
= form_with model: @question, class: 'hidden', html: { id: "edit-question-form" } do |f|
  = render 'shared/errors', resource: @question
  p
  = f.label :title, 'Your title'
  = f.text_field :title
  p
  = f.label :body, 'Your body'
  = f.text_area :body
  p
  = f.label :files
  = f.file_field :files, multiple: true, direct_upload: true
  p Links:
  p
    = f.fields_for :links do |l|
    .links
      = link_to_add_association 'add link', f, :links
  p
  = f.submit 'Save'

app/views/questions/_link_fields.html.slim
.nested-fields
  = f.label :name, 'Link'
  = f.text_field :name
  = f.label :url
  = f.text_field :url
  = link_to_remove_association "remove task", f

app/views/questions/_question.html.slim
.question-title = @question.title
.question-body = @question.body
.question-errors


.vote
  = render 'shared/vote', resource: question

- if question.badge.present?
  .badge
    p Badge:
    = image_tag question.badge.image, title: question.badge.title, size: "70x70"
    p = question.badge.title

.links
  p Links:
  ul
    = render question.links, resource: question

- if @question.files.attached?
  - @question.files.each do |file|
    div class = "attachment-#{file.id}"
      p= link_to file.filename.to_s, url_for(file)
      - if current_user&.author?(question)
            = link_to 'remove', attachment_path(file), class: 'delete-attachment-link', remote: true, method: :delete

- if current_user&.author?(@question)
  = link_to 'Edit question', '#', class: 'edit-question-link'
  = link_to 'Delete question', question_path(@question), method: :delete
  = render 'form'

app/views/questions/index.html.slim
= link_to 'Ask question', new_question_path

- @questions.each do |question|
  p= link_to question.title, question_path(question)

app/views/questions/new.html.slim
= render 'shared/errors', resource: @question

= form_with model: @question do |f|
  p
    = f.label :title
    = f.text_field :title
  p
    = f.label :body
    = f.text_area :body
  p
    = f.label :files
    = f.file_field :files, multiple: true

  p Links:
  p
    =f.fields_for :links do |l|
      = render 'link_fields', f: l
    .links
      = link_to_add_association 'add link', f, :links

  p Badge:
  p
    = f.fields_for :badge do |b|
      p
        = b.label :title, 'Badge title'
        = b.text_field :title
      p
        = b.label :image, 'Add a badge?'
        = b.file_field :image, class: 'badge upload'
      p
  p= f.submit 'Ask'

app/views/questions/show.html.slim
.question
  = render @question

.answers
  = render @question.answers

= render 'answers/form'

= link_to 'Back', questions_path

app/views/questions/update.js.erb
$('.question-errors').html('<%= render 'shared/errors', resource: @question %>');

<% if !@question.errors.present? %>
  $('.question').html('<%= j render @question %>');
  $('form#edit-question-form').hide()
  $('.edit-question-link').show()
<% end %>